from . import models, util
from .agents import (
    TOOL_APPROVAL_HOOK_TYPE,
    Agent,
    AgentTool,
    Aggregate,
    ConcatAggregator,
    Context,
    LastAggregator,
    MessageAggregator,
    MessageBundle,
    SimpleAggregator,
    StreamingStatusTool,
    StreamingTextTool,
    SubAgentTool,
    Tool,
    ToolCall,
    ToolCallLike,
    ToolRunner,
    agent,
    cancel_hook,
    hook,
    mcp,
    middleware,
    resolve_hook,
    tool,
    tool_result,
    yield_from,
)
from .agents.middleware import Middleware
from .models import (
    Client,
    Executor,
    GenerateExecutor,
    GenerateRequest,
    ImageParams,
    Model,
    Provider,
    Stream,
    StreamExecutor,
    StreamParams,
    StreamRequest,
    VideoParams,
    ai_gateway,
    anthropic,
    check_connection,
    generate,
    openai,
    stream,
)
from .types import events, messages, tools
from .types.builders import (
    assistant_message,
    file_part,
    system_message,
    thinking,
    tool_message,
    tool_result_part,
    user_message,
)

__all__ = [
    # Builders (from types/builders)
    "user_message",
    "assistant_message",
    "system_message",
    "tool_message",
    "tool_result",
    "tool_result_part",
    "file_part",
    "thinking",
    # Models (from models/)
    "Model",
    "Provider",
    "ImageParams",
    "VideoParams",
    "StreamParams",
    "Client",
    "Stream",
    "StreamRequest",
    "GenerateRequest",
    "Executor",
    "StreamExecutor",
    "GenerateExecutor",
    "check_connection",
    "stream",
    "generate",
    "models",
    # Provider factories
    "openai",
    "anthropic",
    "ai_gateway",
    # Agents — primary API
    "Agent",
    "AgentTool",
    "agent",
    "Context",
    # Agents — tools
    "Tool",
    "ToolCall",
    "ToolCallLike",
    "ToolRunner",
    "tool",
    # Agents — aggregators
    "Aggregate",
    "ConcatAggregator",
    "LastAggregator",
    "MessageAggregator",
    "MessageBundle",
    "SimpleAggregator",
    "StreamingTextTool",
    "SubAgentTool",
    "StreamingStatusTool",
    # Agents — composition
    "yield_from",
    # Agents — hooks
    "hook",
    "resolve_hook",
    "cancel_hook",
    "TOOL_APPROVAL_HOOK_TYPE",
    # Middleware
    "Middleware",
    "middleware",
    # Submodules
    "events",
    "messages",
    "mcp",
    "tools",
    "util",
]
